services:

  front:
    container_name: moderate-quality-check-tool-front
    build: 
      context: src/front
      dockerfile: Dockerfile.dev
    image: moderate-quality-check-tool/moderate-quality-check-tool-app:$DOCKER_IMAGE_TAG
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=3000
      - VITE_API_BASE_URL=http://localhost:5501
    restart: always
    ports:
      - ${SERVICE_PORT_FRONTEND}:5173
    volumes:
      - ./src/front:/app
      - /app/node_modules
  
  back:
    container_name: moderate-quality-check-tool-back
    build: 
      context: src/back
      dockerfile: Dockerfile.dev
    image: moderate-quality-check-tool/moderate-quality-check-tool-report-svc:$DOCKER_IMAGE_TAG
    ports:
      - 5501:5000 # <---- <host>:<container>
    restart: always
    volumes:
      - ./src/back:/src

  docx-to-pdf:
    image: moalhaddar/docx-to-pdf:2.1.0-12
    container_name: moderate-quality-check-tool-docx-to-pdf
    # ports:
      # - 55002:8080
    environment:
      - pool.size=2
    # volumes:
    #   - ./fonts:/usr/share/fonts/custom
    restart: always
