services:

  front:
    container_name: moderate-quality-check-tool-front
    build: src/front
    image: moderate-quality-check-tool/moderate-quality-check-tool-app:$DOCKER_IMAGE_TAG
    environment:
      - MODERATE_RULES_SVC_PROXY_PASS_URL=http://back:5000
      # - MODERATE_REPORT_SVC_PROXY_PASS_URL=http://back:5000
    restart: always
    ports:
      - ${SERVICE_PORT_FRONTEND}:80
  
  back:
    container_name: moderate-quality-check-tool-back
    build: src/back
    image: moderate-quality-check-tool/moderate-quality-check-tool-report-svc:$DOCKER_IMAGE_TAG
    restart: always

  # docx-to-pdf:
  #   image: moalhaddar/docx-to-pdf:2.1.0-12
  #   container_name: moderate-quality-check-tool-docx-to-pdf
  #   environment:
  #     - pool.size=2
  #   restart: always
