version: "3"

dotenv: [".env"]

vars:
  ENV: "{{.ENV | default `prod`}}"

  compose_file:
    sh: |
      if [ "{{.ENV}}" = "prod" ]; then
        echo "docker-compose.prod.yaml"
      else
        echo "docker-compose.dev.yaml"
      fi

tasks:

  build:
    desc: "Builds Docker images based on the selected environment (dev or prod)."
    cmds:
      - docker compose -f {{.compose_file}} build --no-cache
      # - chmod -R 777 ./resultados

  start:
    desc: "Starts containers in the background using the selected environment (dev or prod), removing orphan containers."
    cmds:
      - docker compose -f ${PWD}/{{.compose_file}} up -d --remove-orphans

  logs:
    desc: "Displays real-time logs for the 'back' and 'front' services in the selected environment (dev or prod)."
    cmds:
      - |
        if [ -n "{{.CLI_ARGS}}" ]; then
          docker compose -f ${PWD}/{{.compose_file}} logs -f {{.CLI_ARGS}}
        else
          docker compose -f ${PWD}/{{.compose_file}} logs -f back front
        fi

  stop:
    desc: "Stops and removes containers, networks, and orphan volumes in the selected environment (dev or prod)."
    cmds:
      - docker compose -f ${PWD}/{{.compose_file}} down --remove-orphans

  clear:
    desc: "Stops and removes containers, networks, images, and volumes in the selected environment (dev or prod)."
    cmds:
      - docker compose -f ${PWD}/{{.compose_file}} down --remove-orphans --rmi all --volumes

  status:
    desc: "Shows the environment set and the state of the containers defined in the compose file"
    silent: true
    cmds:
      - echo "Using environment:" {{.ENV}}
      - docker compose -f {{.compose_file}} ps

  add-i18n-string:
    desc: Añadir un nuevo string a los archivos de i18n (solo en entorno dev)
    preconditions:
      - sh: '[ "{{.ENV}}" = "dev" ]'
        platforms: [linux, darwin]
        msg: "Esta tarea solo puede ejecutarse si ENV=dev (Unix)"
      - cmd: powershell -Command "if ('{{.ENV}}' -ne 'dev') { exit 1 }"
        platforms: [windows]
        msg: "Esta tarea solo puede ejecutarse si ENV=dev (Windows)"
    cmds:
      - cmd: powershell.exe -File ./add-i18n-string.ps1
        platforms: [windows]
      - cmd: bash ./add-i18n-string.sh
        platforms: [linux, darwin]
