version: "3"

tasks:

  build:
    - docker compose -f docker-compose.yaml build --no-cache

  start:
      - docker compose -f ${PWD}/docker-compose.yaml up -d --remove-orphans

  logs:
    - docker compose -f ${PWD}/docker-compose.yaml logs -f back front

  stop:
    - docker compose  -f ${PWD}/docker-compose.yaml down
