FROM python:3.12-alpine

ENV PYTHONPATH="${PYTHONPATH}:/src"

WORKDIR /src
    
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
  
COPY . .
# COPY app.py app.py

ENV FLASK_APP=app:app

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]
