FROM python:3.12-slim-bullseye

ENV PYTHONPATH="${PYTHONPATH}:/src"

WORKDIR /src
    
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
  
COPY . .
# COPY app.py app.py

ENV FLASK_APP=app:app
ENV FLASK_DEBUG=1
ENV FLASK_ENV=development

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--debug"]
